queue_rules:
  - name: default
    queue_conditions:
      - "#approved-reviews-by>=1"
      - label=merge me
      - check-success=api-tests
      - check-success=compose-tests
      - check-success=web-tests
    merge_conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=api-tests
      - check-success=compose-tests
      - check-success=web-tests
    merge_method: merge

pull_request_rules:
  - actions:
      delete_head_branch: {}
    name: Delete head branch after merge
    conditions:
      - merged
  - name: Automatic merge on approval
    conditions: []
    actions:
      queue:
