pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - label=merge me
      - check-success=Haskell GHC
      - check-success=check-python
      - check-success=check-k8s
      - check-success=docker
    actions:
      merge:
        method: merge
        strict: smart+fasttrack
  - actions:
      delete_head_branch: {}
    name: Delete head branch after merge
    conditions:
      - merged
