# Monocle.
# Copyright (C) 2019-2020 Monocle authors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# base image
FROM registry.fedoraproject.org/fedora:33

RUN dnf update -y && dnf install -y nodejs

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# copy files to install js modules
COPY package.json /app/
COPY bsconfig.json /app/
COPY package-lock.json /app/

# install dependencies
RUN npm install

# copy source files
COPY build.js /app/
COPY public /app/public/
COPY src /app/src/

# install dependencies
RUN npm run build

################################################################################
FROM registry.fedoraproject.org/fedora:33

RUN dnf update -y && dnf install -y nginx && dnf clean all

COPY --from=0 /app/build /app
COPY conf/start.sh /bin/
COPY conf/nginx.conf /etc/nginx/conf.d/monocle.conf

CMD /bin/start.sh
