#!/usr/bin/env python
# Copyright (C) 2021 Monocle authors
# SPDX-License-Identifier: AGPL-3.0-or-later

import argparse
import os
import sys


def run(cmd):
    if os.system(cmd) != 0:
        raise RuntimeError("Command: `%s` failed", cmd)


def main():
    args = sys.argv[1:]
    name = "data/" + "-".join(["devel"] + args)
    if args == ["devel"]:
        run(f"echo './package.dhall True' | dhall-to-yaml > {name}.yaml")
        run(f"kubectl apply -f {name}.yaml")
    elif args == ["stop"]:
        run(f"kubectl delete -f {name}.yaml")
    else:
        print("usage: deploy|devel|build")
        exit(1)


if __name__ == "__main__":
    main()
