---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: crawler
    app.kubernetes.io/component: crawler
    app.kubernetes.io/part-of: monocle
  name: crawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: crawler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: crawler
        app.kubernetes.io/component: crawler
        app.kubernetes.io/part-of: monocle
    spec:
      containers:
        - args:
            - bash
            - -c
            - "export $(cat /etc/monocle-secrets/.secrets) && monocle crawler"
          env:
            - name: MONOCLE_PUBLIC_URL
              value: http://api:8080
          image: quay.io/change-metrics/monocle:1.8.0
          name: crawler
          resources: {}
          livenessProbe:
            httpGet:
              path: /health
              port: 9001
            failureThreshold: 6
            timeoutSeconds: 60
          volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
            - mountPath: /etc/monocle-secrets
              name: monocle-secret-volume
      restartPolicy: Always
      volumes:
        - name: monocle-config-volume
          configMap:
            defaultMode: 420
            name: monocle-config
        - name: monocle-secret-volume
          secret:
            secretName: monocle-secrets
