@startuml
title Monocle architecture

package "backend" {
  database "elastic" as Datastore
  collections "api" as Api
  agent "crawler" as Worker
}
actor user as User

Api --> Datastore
Api <--> Worker
User --> Api
@enduml
