@startuml
title Monocle architecture

package "backend" {
  database "elastic" as Datastore
  collections "api" as Api
  agent "crawler" as Worker
  cloud "web" as Proxy

  package "legacy" {
    agent "crawler" as LegacyWorker
    agent "api" as LegacyApi
  }
}
actor user as User

Api --> Datastore
Api <--> Worker
Proxy -> Api
User --> Proxy
Proxy -> LegacyApi
LegacyApi --> Datastore
LegacyWorker --> Datastore
@enduml
