---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: monocle
  name: api
spec:
  ports:
    - name: http-rest-api
      port: 9898
      targetPort: 9898
  selector:
    app.kubernetes.io/name: api
status:
  loadBalancer: {}
