---
apiVersion: batch/v1
kind: CronJob
metadata:
  creationTimestamp: "2021-11-22T12:42:28Z"
  labels:
    app.kubernetes.io/component: crawler
    app.kubernetes.io/name: crawler-legacy
    app.kubernetes.io/part-of: monocle
  name: crawler-legacy
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 0
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: crawler-legacy
    spec:
      template:
        metadata:
          creationTimestamp: null
          labels:
            app.kubernetes.io/component: crawler
            app.kubernetes.io/name: crawler-legacy
            app.kubernetes.io/part-of: monocle
        spec:
          containers:
          - args:
            - monocle
            - --elastic-conn
            - elastic:9200
            - crawler
            - --config
            - /etc/monocle/config.yaml
            env:
            - name: APP_ID
            - name: APP_KEY_PATH
              value: /etc/monocle/app_key.rsa
            image: quay.io/change-metrics/monocle_backend:latest
            name: crawler-legacy
            volumeMounts:
            - mountPath: /etc/monocle
              name: monocle-config-volume
            - mountPath: /var/lib/crawler
              name: crawler-dump-data-volume
          terminationGracePeriodSeconds: 30
          volumes:
          - configMap:
              defaultMode: 420
              name: monocle-config
            name: monocle-config-volume
          - emptyDir: {}
            name: crawler-dump-data-volume
          restartPolicy: Never
  schedule: '0 * */1 * *'
  successfulJobsHistoryLimit: 3
  suspend: false
status: {}
