---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: elastic
    app.kubernetes.io/part-of: monocle
  name: elastic
spec:
  ports:
    - name: rest
      port: 9200
      targetPort: 9200
  selector:
    app.kubernetes.io/name: elastic
status:
  loadBalancer: {}
