---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/name: elastic
    app.kubernetes.io/component: elastic
    app.kubernetes.io/part-of: monocle
  name: elastic-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
