---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: web
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: monocle
  name: web
spec:
  ports:
    - name: web
      port: 8080
      targetPort: 8080
  selector:
    app.kubernetes.io/name: web
status:
  loadBalancer: {}
