# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monocle/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="monocle/auth.proto",
    package="monocle_auth",
    syntax="proto3",
    serialized_options=b"Z\014monocle/auth",
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x12monocle/auth.proto\x12\x0cmonocle_auth"\x1d\n\rWhoAmIRequest\x12\x0c\n\x04noop\x18\x01 \x01(\t" \n\x0eWhoAmIResponse\x12\x0e\n\x06userid\x18\x01 \x01(\tB\x0eZ\x0cmonocle/authb\x06proto3',
)


_WHOAMIREQUEST = _descriptor.Descriptor(
    name="WhoAmIRequest",
    full_name="monocle_auth.WhoAmIRequest",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="noop",
            full_name="monocle_auth.WhoAmIRequest.noop",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=36,
    serialized_end=65,
)


_WHOAMIRESPONSE = _descriptor.Descriptor(
    name="WhoAmIResponse",
    full_name="monocle_auth.WhoAmIResponse",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="userid",
            full_name="monocle_auth.WhoAmIResponse.userid",
            index=0,
            number=1,
            type=9,
            cpp_type=9,
            label=1,
            has_default_value=False,
            default_value=b"".decode("utf-8"),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=67,
    serialized_end=99,
)

DESCRIPTOR.message_types_by_name["WhoAmIRequest"] = _WHOAMIREQUEST
DESCRIPTOR.message_types_by_name["WhoAmIResponse"] = _WHOAMIRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WhoAmIRequest = _reflection.GeneratedProtocolMessageType(
    "WhoAmIRequest",
    (_message.Message,),
    {
        "DESCRIPTOR": _WHOAMIREQUEST,
        "__module__": "monocle.auth_pb2"
        # @@protoc_insertion_point(class_scope:monocle_auth.WhoAmIRequest)
    },
)
_sym_db.RegisterMessage(WhoAmIRequest)

WhoAmIResponse = _reflection.GeneratedProtocolMessageType(
    "WhoAmIResponse",
    (_message.Message,),
    {
        "DESCRIPTOR": _WHOAMIRESPONSE,
        "__module__": "monocle.auth_pb2"
        # @@protoc_insertion_point(class_scope:monocle_auth.WhoAmIResponse)
    },
)
_sym_db.RegisterMessage(WhoAmIResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
