"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor = ...

class TaskData(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    UPDATED_AT_FIELD_NUMBER: builtins.int
    CHANGE_URL_FIELD_NUMBER: builtins.int
    TTYPE_FIELD_NUMBER: builtins.int
    TID_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    SEVERITY_FIELD_NUMBER: builtins.int
    PRIORITY_FIELD_NUMBER: builtins.int
    SCORE_FIELD_NUMBER: builtins.int
    PREFIX_FIELD_NUMBER: builtins.int
    change_url: typing.Text = ...
    ttype: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    tid: typing.Text = ...
    url: typing.Text = ...
    title: typing.Text = ...
    severity: typing.Text = ...
    priority: typing.Text = ...
    score: builtins.int = ...
    prefix: typing.Text = ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        change_url: typing.Text = ...,
        ttype: typing.Optional[typing.Iterable[typing.Text]] = ...,
        tid: typing.Text = ...,
        url: typing.Text = ...,
        title: typing.Text = ...,
        severity: typing.Text = ...,
        priority: typing.Text = ...,
        score: builtins.int = ...,
        prefix: typing.Text = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["updated_at", b"updated_at"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "change_url",
            b"change_url",
            "prefix",
            b"prefix",
            "priority",
            b"priority",
            "score",
            b"score",
            "severity",
            b"severity",
            "tid",
            b"tid",
            "title",
            b"title",
            "ttype",
            b"ttype",
            "updated_at",
            b"updated_at",
            "url",
            b"url",
        ],
    ) -> None: ...

global___TaskData = TaskData

class SuggestionsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INDEX_FIELD_NUMBER: builtins.int
    index: typing.Text = ...
    def __init__(
        self,
        *,
        index: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["index", b"index"]
    ) -> None: ...

global___SuggestionsRequest = SuggestionsRequest

class SuggestionsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TASK_TYPES_FIELD_NUMBER: builtins.int
    AUTHORS_FIELD_NUMBER: builtins.int
    APPROVALS_FIELD_NUMBER: builtins.int
    PRIORITIES_FIELD_NUMBER: builtins.int
    SEVERITIES_FIELD_NUMBER: builtins.int
    PROJECTS_FIELD_NUMBER: builtins.int
    GROUPS_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    task_types: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    authors: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    approvals: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    priorities: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    severities: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    projects: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    groups: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    labels: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    def __init__(
        self,
        *,
        task_types: typing.Optional[typing.Iterable[typing.Text]] = ...,
        authors: typing.Optional[typing.Iterable[typing.Text]] = ...,
        approvals: typing.Optional[typing.Iterable[typing.Text]] = ...,
        priorities: typing.Optional[typing.Iterable[typing.Text]] = ...,
        severities: typing.Optional[typing.Iterable[typing.Text]] = ...,
        projects: typing.Optional[typing.Iterable[typing.Text]] = ...,
        groups: typing.Optional[typing.Iterable[typing.Text]] = ...,
        labels: typing.Optional[typing.Iterable[typing.Text]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "approvals",
            b"approvals",
            "authors",
            b"authors",
            "groups",
            b"groups",
            "labels",
            b"labels",
            "priorities",
            b"priorities",
            "projects",
            b"projects",
            "severities",
            b"severities",
            "task_types",
            b"task_types",
        ],
    ) -> None: ...

global___SuggestionsResponse = SuggestionsResponse

class FieldsRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    VERSION_FIELD_NUMBER: builtins.int
    version: typing.Text = ...
    def __init__(
        self,
        *,
        version: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["version", b"version"]
    ) -> None: ...

global___FieldsRequest = FieldsRequest

class Field(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Type(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Type.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        FIELD_DATE = Field.Type.V(0)
        FIELD_NUMBER = Field.Type.V(1)
        FIELD_TEXT = Field.Type.V(2)
        FIELD_BOOL = Field.Type.V(3)
        FIELD_REGEX = Field.Type.V(4)
    class Type(metaclass=_Type):
        V = typing.NewType("V", builtins.int)
    FIELD_DATE = Field.Type.V(0)
    FIELD_NUMBER = Field.Type.V(1)
    FIELD_TEXT = Field.Type.V(2)
    FIELD_BOOL = Field.Type.V(3)
    FIELD_REGEX = Field.Type.V(4)

    NAME_FIELD_NUMBER: builtins.int
    DESCRIPTION_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    name: typing.Text = ...
    description: typing.Text = ...
    type: global___Field.Type.V = ...
    def __init__(
        self,
        *,
        name: typing.Text = ...,
        description: typing.Text = ...,
        type: global___Field.Type.V = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "description", b"description", "name", b"name", "type", b"type"
        ],
    ) -> None: ...

global___Field = Field

class FieldsResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Field
    ]: ...
    def __init__(
        self,
        *,
        fields: typing.Optional[typing.Iterable[global___Field]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["fields", b"fields"]
    ) -> None: ...

global___FieldsResponse = FieldsResponse

class QueryError(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    MESSAGE_FIELD_NUMBER: builtins.int
    POSITION_FIELD_NUMBER: builtins.int
    message: typing.Text = ...
    position: builtins.int = ...
    def __init__(
        self,
        *,
        message: typing.Text = ...,
        position: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "message", b"message", "position", b"position"
        ],
    ) -> None: ...

global___QueryError = QueryError

class CheckRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    INDEX_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    index: typing.Text = ...
    username: typing.Text = ...
    query: typing.Text = ...
    def __init__(
        self,
        *,
        index: typing.Text = ...,
        username: typing.Text = ...,
        query: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "index", b"index", "query", b"query", "username", b"username"
        ],
    ) -> None: ...

global___CheckRequest = CheckRequest

class CheckResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SUCCESS_FIELD_NUMBER: builtins.int
    ERROR_FIELD_NUMBER: builtins.int
    success: typing.Text = ...
    @property
    def error(self) -> global___QueryError: ...
    def __init__(
        self,
        *,
        success: typing.Text = ...,
        error: typing.Optional[global___QueryError] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "error", b"error", "result", b"result", "success", b"success"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "error", b"error", "result", b"result", "success", b"success"
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["result", b"result"]
    ) -> typing_extensions.Literal["success", "error"]: ...

global___CheckResponse = CheckResponse

class Order(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _Direction(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Direction.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        ASC = Order.Direction.V(0)
        DESC = Order.Direction.V(1)
    class Direction(metaclass=_Direction):
        V = typing.NewType("V", builtins.int)
    ASC = Order.Direction.V(0)
    DESC = Order.Direction.V(1)

    FIELD_FIELD_NUMBER: builtins.int
    DIRECTION_FIELD_NUMBER: builtins.int
    field: typing.Text = ...
    direction: global___Order.Direction.V = ...
    def __init__(
        self,
        *,
        field: typing.Text = ...,
        direction: global___Order.Direction.V = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "direction", b"direction", "field", b"field"
        ],
    ) -> None: ...

global___Order = Order

class QueryRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    class _QueryType(
        google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[QueryType.V],
        builtins.type,
    ):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor = ...
        QUERY_CHANGE = QueryRequest.QueryType.V(0)
        QUERY_REPOS_SUMMARY = QueryRequest.QueryType.V(2)
        QUERY_TOP_AUTHORS_CHANGES_CREATED = QueryRequest.QueryType.V(3)
        QUERY_TOP_AUTHORS_CHANGES_MERGED = QueryRequest.QueryType.V(4)
        QUERY_TOP_AUTHORS_CHANGES_REVIEWED = QueryRequest.QueryType.V(5)
        QUERY_TOP_AUTHORS_CHANGES_COMMENTED = QueryRequest.QueryType.V(6)
        QUERY_TOP_REVIEWED_AUTHORS = QueryRequest.QueryType.V(7)
        QUERY_TOP_COMMENTED_AUTHORS = QueryRequest.QueryType.V(8)
        QUERY_TOP_AUTHORS_PEERS = QueryRequest.QueryType.V(9)
        QUERY_NEW_CHANGES_AUTHORS = QueryRequest.QueryType.V(10)
        QUERY_CHANGES_REVIEW_STATS = QueryRequest.QueryType.V(20)
        QUERY_CHANGES_LIFECYCLE_STATS = QueryRequest.QueryType.V(21)
        QUERY_ACTIVE_AUTHORS_STATS = QueryRequest.QueryType.V(22)
        QUERY_CHANGE_AND_EVENTS = QueryRequest.QueryType.V(30)
        QUERY_CHANGES_TOPS = QueryRequest.QueryType.V(31)
    class QueryType(metaclass=_QueryType):
        V = typing.NewType("V", builtins.int)
    QUERY_CHANGE = QueryRequest.QueryType.V(0)
    QUERY_REPOS_SUMMARY = QueryRequest.QueryType.V(2)
    QUERY_TOP_AUTHORS_CHANGES_CREATED = QueryRequest.QueryType.V(3)
    QUERY_TOP_AUTHORS_CHANGES_MERGED = QueryRequest.QueryType.V(4)
    QUERY_TOP_AUTHORS_CHANGES_REVIEWED = QueryRequest.QueryType.V(5)
    QUERY_TOP_AUTHORS_CHANGES_COMMENTED = QueryRequest.QueryType.V(6)
    QUERY_TOP_REVIEWED_AUTHORS = QueryRequest.QueryType.V(7)
    QUERY_TOP_COMMENTED_AUTHORS = QueryRequest.QueryType.V(8)
    QUERY_TOP_AUTHORS_PEERS = QueryRequest.QueryType.V(9)
    QUERY_NEW_CHANGES_AUTHORS = QueryRequest.QueryType.V(10)
    QUERY_CHANGES_REVIEW_STATS = QueryRequest.QueryType.V(20)
    QUERY_CHANGES_LIFECYCLE_STATS = QueryRequest.QueryType.V(21)
    QUERY_ACTIVE_AUTHORS_STATS = QueryRequest.QueryType.V(22)
    QUERY_CHANGE_AND_EVENTS = QueryRequest.QueryType.V(30)
    QUERY_CHANGES_TOPS = QueryRequest.QueryType.V(31)

    INDEX_FIELD_NUMBER: builtins.int
    USERNAME_FIELD_NUMBER: builtins.int
    QUERY_FIELD_NUMBER: builtins.int
    QUERY_TYPE_FIELD_NUMBER: builtins.int
    ORDER_FIELD_NUMBER: builtins.int
    LIMIT_FIELD_NUMBER: builtins.int
    CHANGE_ID_FIELD_NUMBER: builtins.int
    index: typing.Text = ...
    username: typing.Text = ...
    query: typing.Text = ...
    query_type: global___QueryRequest.QueryType.V = ...
    limit: builtins.int = ...
    change_id: typing.Text = ...
    @property
    def order(self) -> global___Order: ...
    def __init__(
        self,
        *,
        index: typing.Text = ...,
        username: typing.Text = ...,
        query: typing.Text = ...,
        query_type: global___QueryRequest.QueryType.V = ...,
        order: typing.Optional[global___Order] = ...,
        limit: builtins.int = ...,
        change_id: typing.Text = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["order", b"order"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "change_id",
            b"change_id",
            "index",
            b"index",
            "limit",
            b"limit",
            "order",
            b"order",
            "query",
            b"query",
            "query_type",
            b"query_type",
            "username",
            b"username",
        ],
    ) -> None: ...

global___QueryRequest = QueryRequest

class File(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ADDITIONS_FIELD_NUMBER: builtins.int
    DELETIONS_FIELD_NUMBER: builtins.int
    PATH_FIELD_NUMBER: builtins.int
    additions: builtins.int = ...
    deletions: builtins.int = ...
    path: typing.Text = ...
    def __init__(
        self,
        *,
        additions: builtins.int = ...,
        deletions: builtins.int = ...,
        path: typing.Text = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "additions", b"additions", "deletions", b"deletions", "path", b"path"
        ],
    ) -> None: ...

global___File = File

class Commit(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    SHA_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    AUTHORED_AT_FIELD_NUMBER: builtins.int
    COMMITTER_FIELD_NUMBER: builtins.int
    COMMITTED_AT_FIELD_NUMBER: builtins.int
    ADDITIONS_FIELD_NUMBER: builtins.int
    DELETIONS_FIELD_NUMBER: builtins.int
    sha: typing.Text = ...
    title: typing.Text = ...
    author: typing.Text = ...
    committer: typing.Text = ...
    additions: builtins.int = ...
    deletions: builtins.int = ...
    @property
    def authored_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def committed_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        sha: typing.Text = ...,
        title: typing.Text = ...,
        author: typing.Text = ...,
        authored_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        committer: typing.Text = ...,
        committed_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        additions: builtins.int = ...,
        deletions: builtins.int = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "authored_at", b"authored_at", "committed_at", b"committed_at"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "additions",
            b"additions",
            "author",
            b"author",
            "authored_at",
            b"authored_at",
            "committed_at",
            b"committed_at",
            "committer",
            b"committer",
            "deletions",
            b"deletions",
            "sha",
            b"sha",
            "title",
            b"title",
        ],
    ) -> None: ...

global___Commit = Commit

class Change(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CHANGE_ID_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    TITLE_FIELD_NUMBER: builtins.int
    URL_FIELD_NUMBER: builtins.int
    REPOSITORY_FULLNAME_FIELD_NUMBER: builtins.int
    STATE_FIELD_NUMBER: builtins.int
    BRANCH_FIELD_NUMBER: builtins.int
    TARGET_BRANCH_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    UPDATED_AT_FIELD_NUMBER: builtins.int
    MERGED_AT_FIELD_NUMBER: builtins.int
    MERGED_BY_FIELD_NUMBER: builtins.int
    TEXT_FIELD_NUMBER: builtins.int
    ADDITIONS_FIELD_NUMBER: builtins.int
    DELETIONS_FIELD_NUMBER: builtins.int
    APPROVAL_FIELD_NUMBER: builtins.int
    ASSIGNEES_FIELD_NUMBER: builtins.int
    LABELS_FIELD_NUMBER: builtins.int
    DRAFT_FIELD_NUMBER: builtins.int
    MERGEABLE_FIELD_NUMBER: builtins.int
    CHANGED_FILES_FIELD_NUMBER: builtins.int
    CHANGED_FILES_COUNT_FIELD_NUMBER: builtins.int
    COMMITS_FIELD_NUMBER: builtins.int
    COMMITS_COUNT_FIELD_NUMBER: builtins.int
    TASK_DATA_FIELD_NUMBER: builtins.int
    change_id: typing.Text = ...
    author: typing.Text = ...
    title: typing.Text = ...
    url: typing.Text = ...
    repository_fullname: typing.Text = ...
    state: typing.Text = ...
    branch: typing.Text = ...
    target_branch: typing.Text = ...
    merged_by: typing.Text = ...
    text: typing.Text = ...
    additions: builtins.int = ...
    deletions: builtins.int = ...
    approval: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    assignees: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    labels: google.protobuf.internal.containers.RepeatedScalarFieldContainer[
        typing.Text
    ] = ...
    draft: builtins.bool = ...
    mergeable: builtins.bool = ...
    changed_files_count: builtins.int = ...
    commits_count: builtins.int = ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def updated_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def merged_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def changed_files(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___File
    ]: ...
    @property
    def commits(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Commit
    ]: ...
    @property
    def task_data(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TaskData
    ]: ...
    def __init__(
        self,
        *,
        change_id: typing.Text = ...,
        author: typing.Text = ...,
        title: typing.Text = ...,
        url: typing.Text = ...,
        repository_fullname: typing.Text = ...,
        state: typing.Text = ...,
        branch: typing.Text = ...,
        target_branch: typing.Text = ...,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        updated_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        merged_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        merged_by: typing.Text = ...,
        text: typing.Text = ...,
        additions: builtins.int = ...,
        deletions: builtins.int = ...,
        approval: typing.Optional[typing.Iterable[typing.Text]] = ...,
        assignees: typing.Optional[typing.Iterable[typing.Text]] = ...,
        labels: typing.Optional[typing.Iterable[typing.Text]] = ...,
        draft: builtins.bool = ...,
        mergeable: builtins.bool = ...,
        changed_files: typing.Optional[typing.Iterable[global___File]] = ...,
        changed_files_count: builtins.int = ...,
        commits: typing.Optional[typing.Iterable[global___Commit]] = ...,
        commits_count: builtins.int = ...,
        task_data: typing.Optional[typing.Iterable[global___TaskData]] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "created_at",
            b"created_at",
            "merged_at",
            b"merged_at",
            "merged_by",
            b"merged_by",
            "merged_byM",
            b"merged_byM",
            "updated_at",
            b"updated_at",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "additions",
            b"additions",
            "approval",
            b"approval",
            "assignees",
            b"assignees",
            "author",
            b"author",
            "branch",
            b"branch",
            "change_id",
            b"change_id",
            "changed_files",
            b"changed_files",
            "changed_files_count",
            b"changed_files_count",
            "commits",
            b"commits",
            "commits_count",
            b"commits_count",
            "created_at",
            b"created_at",
            "deletions",
            b"deletions",
            "draft",
            b"draft",
            "labels",
            b"labels",
            "mergeable",
            b"mergeable",
            "merged_at",
            b"merged_at",
            "merged_by",
            b"merged_by",
            "merged_byM",
            b"merged_byM",
            "repository_fullname",
            b"repository_fullname",
            "state",
            b"state",
            "target_branch",
            b"target_branch",
            "task_data",
            b"task_data",
            "text",
            b"text",
            "title",
            b"title",
            "updated_at",
            b"updated_at",
            "url",
            b"url",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["merged_byM", b"merged_byM"]
    ) -> typing_extensions.Literal["merged_by"]: ...

global___Change = Change

class Changes(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CHANGES_FIELD_NUMBER: builtins.int
    @property
    def changes(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Change
    ]: ...
    def __init__(
        self,
        *,
        changes: typing.Optional[typing.Iterable[global___Change]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["changes", b"changes"]
    ) -> None: ...

global___Changes = Changes

class ChangeEvent(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ID_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    CHANGE_ID_FIELD_NUMBER: builtins.int
    CREATED_AT_FIELD_NUMBER: builtins.int
    ON_CREATED_AT_FIELD_NUMBER: builtins.int
    AUTHOR_FIELD_NUMBER: builtins.int
    ON_AUTHOR_FIELD_NUMBER: builtins.int
    BRANCH_FIELD_NUMBER: builtins.int
    id: typing.Text = ...
    type: typing.Text = ...
    change_id: typing.Text = ...
    author: typing.Text = ...
    on_author: typing.Text = ...
    branch: typing.Text = ...
    @property
    def created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def on_created_at(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        id: typing.Text = ...,
        type: typing.Text = ...,
        change_id: typing.Text = ...,
        created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        on_created_at: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        author: typing.Text = ...,
        on_author: typing.Text = ...,
        branch: typing.Text = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "created_at", b"created_at", "on_created_at", b"on_created_at"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "author",
            b"author",
            "branch",
            b"branch",
            "change_id",
            b"change_id",
            "created_at",
            b"created_at",
            "id",
            b"id",
            "on_author",
            b"on_author",
            "on_created_at",
            b"on_created_at",
            "type",
            b"type",
        ],
    ) -> None: ...

global___ChangeEvent = ChangeEvent

class ChangeAndEvents(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CHANGE_FIELD_NUMBER: builtins.int
    EVENTS_FIELD_NUMBER: builtins.int
    @property
    def change(self) -> global___Change: ...
    @property
    def events(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___ChangeEvent
    ]: ...
    def __init__(
        self,
        *,
        change: typing.Optional[global___Change] = ...,
        events: typing.Optional[typing.Iterable[global___ChangeEvent]] = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["change", b"change"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal["change", b"change", "events", b"events"],
    ) -> None: ...

global___ChangeAndEvents = ChangeAndEvents

class ReviewCount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTHORS_COUNT_FIELD_NUMBER: builtins.int
    EVENTS_COUNT_FIELD_NUMBER: builtins.int
    authors_count: builtins.int = ...
    events_count: builtins.int = ...
    def __init__(
        self,
        *,
        authors_count: builtins.int = ...,
        events_count: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "authors_count", b"authors_count", "events_count", b"events_count"
        ],
    ) -> None: ...

global___ReviewCount = ReviewCount

class Histo(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    DATE_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    date: typing.Text = ...
    count: builtins.int = ...
    def __init__(
        self,
        *,
        date: typing.Text = ...,
        count: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["count", b"count", "date", b"date"]
    ) -> None: ...

global___Histo = Histo

class ReviewStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    COMMENT_COUNT_FIELD_NUMBER: builtins.int
    REVIEW_COUNT_FIELD_NUMBER: builtins.int
    COMMENT_DELAY_FIELD_NUMBER: builtins.int
    REVIEW_DELAY_FIELD_NUMBER: builtins.int
    COMMENT_HISTO_FIELD_NUMBER: builtins.int
    REVIEW_HISTO_FIELD_NUMBER: builtins.int
    comment_delay: builtins.int = ...
    review_delay: builtins.int = ...
    @property
    def comment_count(self) -> global___ReviewCount: ...
    @property
    def review_count(self) -> global___ReviewCount: ...
    @property
    def comment_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def review_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    def __init__(
        self,
        *,
        comment_count: typing.Optional[global___ReviewCount] = ...,
        review_count: typing.Optional[global___ReviewCount] = ...,
        comment_delay: builtins.int = ...,
        review_delay: builtins.int = ...,
        comment_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        review_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "comment_count", b"comment_count", "review_count", b"review_count"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "comment_count",
            b"comment_count",
            "comment_delay",
            b"comment_delay",
            "comment_histo",
            b"comment_histo",
            "review_count",
            b"review_count",
            "review_delay",
            b"review_delay",
            "review_histo",
            b"review_histo",
        ],
    ) -> None: ...

global___ReviewStats = ReviewStats

class ActivityStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CHANGE_AUTHORS_FIELD_NUMBER: builtins.int
    COMMENT_AUTHORS_FIELD_NUMBER: builtins.int
    REVIEW_AUTHORS_FIELD_NUMBER: builtins.int
    COMMENTS_HISTO_FIELD_NUMBER: builtins.int
    REVIEWS_HISTO_FIELD_NUMBER: builtins.int
    CHANGES_HISTO_FIELD_NUMBER: builtins.int
    change_authors: builtins.int = ...
    comment_authors: builtins.int = ...
    review_authors: builtins.int = ...
    @property
    def comments_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def reviews_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def changes_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    def __init__(
        self,
        *,
        change_authors: builtins.int = ...,
        comment_authors: builtins.int = ...,
        review_authors: builtins.int = ...,
        comments_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        reviews_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        changes_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "change_authors",
            b"change_authors",
            "changes_histo",
            b"changes_histo",
            "comment_authors",
            b"comment_authors",
            "comments_histo",
            b"comments_histo",
            "review_authors",
            b"review_authors",
            "reviews_histo",
            b"reviews_histo",
        ],
    ) -> None: ...

global___ActivityStats = ActivityStats

class QueryResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    ERROR_FIELD_NUMBER: builtins.int
    CHANGES_FIELD_NUMBER: builtins.int
    REPOS_SUMMARY_FIELD_NUMBER: builtins.int
    TOP_AUTHORS_FIELD_NUMBER: builtins.int
    AUTHORS_PEERS_FIELD_NUMBER: builtins.int
    NEW_AUTHORS_FIELD_NUMBER: builtins.int
    REVIEW_STATS_FIELD_NUMBER: builtins.int
    LIFECYCLE_STATS_FIELD_NUMBER: builtins.int
    ACTIVITY_STATS_FIELD_NUMBER: builtins.int
    CHANGE_EVENTS_FIELD_NUMBER: builtins.int
    CHANGES_TOPS_FIELD_NUMBER: builtins.int
    @property
    def error(self) -> global___QueryError: ...
    @property
    def changes(self) -> global___Changes: ...
    @property
    def repos_summary(self) -> global___ReposSummary: ...
    @property
    def top_authors(self) -> global___TermsCount: ...
    @property
    def authors_peers(self) -> global___AuthorsPeers: ...
    @property
    def new_authors(self) -> global___TermsCount: ...
    @property
    def review_stats(self) -> global___ReviewStats: ...
    @property
    def lifecycle_stats(self) -> global___LifecycleStats: ...
    @property
    def activity_stats(self) -> global___ActivityStats: ...
    @property
    def change_events(self) -> global___ChangeAndEvents: ...
    @property
    def changes_tops(self) -> global___ChangesTops: ...
    def __init__(
        self,
        *,
        error: typing.Optional[global___QueryError] = ...,
        changes: typing.Optional[global___Changes] = ...,
        repos_summary: typing.Optional[global___ReposSummary] = ...,
        top_authors: typing.Optional[global___TermsCount] = ...,
        authors_peers: typing.Optional[global___AuthorsPeers] = ...,
        new_authors: typing.Optional[global___TermsCount] = ...,
        review_stats: typing.Optional[global___ReviewStats] = ...,
        lifecycle_stats: typing.Optional[global___LifecycleStats] = ...,
        activity_stats: typing.Optional[global___ActivityStats] = ...,
        change_events: typing.Optional[global___ChangeAndEvents] = ...,
        changes_tops: typing.Optional[global___ChangesTops] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "activity_stats",
            b"activity_stats",
            "authors_peers",
            b"authors_peers",
            "change_events",
            b"change_events",
            "changes",
            b"changes",
            "changes_tops",
            b"changes_tops",
            "error",
            b"error",
            "lifecycle_stats",
            b"lifecycle_stats",
            "new_authors",
            b"new_authors",
            "repos_summary",
            b"repos_summary",
            "result",
            b"result",
            "review_stats",
            b"review_stats",
            "top_authors",
            b"top_authors",
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "activity_stats",
            b"activity_stats",
            "authors_peers",
            b"authors_peers",
            "change_events",
            b"change_events",
            "changes",
            b"changes",
            "changes_tops",
            b"changes_tops",
            "error",
            b"error",
            "lifecycle_stats",
            b"lifecycle_stats",
            "new_authors",
            b"new_authors",
            "repos_summary",
            b"repos_summary",
            "result",
            b"result",
            "review_stats",
            b"review_stats",
            "top_authors",
            b"top_authors",
        ],
    ) -> None: ...
    def WhichOneof(
        self, oneof_group: typing_extensions.Literal["result", b"result"]
    ) -> typing_extensions.Literal[
        "error",
        "changes",
        "repos_summary",
        "top_authors",
        "authors_peers",
        "new_authors",
        "review_stats",
        "lifecycle_stats",
        "activity_stats",
        "change_events",
        "changes_tops",
    ]: ...

global___QueryResponse = QueryResponse

class LifecycleStats(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    CREATED_HISTO_FIELD_NUMBER: builtins.int
    UPDATED_HISTO_FIELD_NUMBER: builtins.int
    MERGED_HISTO_FIELD_NUMBER: builtins.int
    ABANDONED_HISTO_FIELD_NUMBER: builtins.int
    CREATED_FIELD_NUMBER: builtins.int
    ABANDONED_FIELD_NUMBER: builtins.int
    MERGED_FIELD_NUMBER: builtins.int
    SELF_MERGED_FIELD_NUMBER: builtins.int
    SELF_MERGED_RATIO_FIELD_NUMBER: builtins.int
    TTM_MEAN_FIELD_NUMBER: builtins.int
    TTM_VARIABILITY_FIELD_NUMBER: builtins.int
    UPDATES_OF_CHANGES_FIELD_NUMBER: builtins.int
    CHANGES_WITH_TESTS_FIELD_NUMBER: builtins.int
    ITERATIONS_PER_CHANGE_FIELD_NUMBER: builtins.int
    COMMITS_PER_CHANGE_FIELD_NUMBER: builtins.int
    abandoned: builtins.int = ...
    merged: builtins.int = ...
    self_merged: builtins.int = ...
    self_merged_ratio: builtins.float = ...
    ttm_mean: builtins.float = ...
    ttm_variability: builtins.float = ...
    updates_of_changes: builtins.int = ...
    changes_with_tests: builtins.float = ...
    iterations_per_change: builtins.float = ...
    commits_per_change: builtins.float = ...
    @property
    def created_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def updated_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def merged_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def abandoned_histo(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___Histo
    ]: ...
    @property
    def created(self) -> global___ReviewCount: ...
    def __init__(
        self,
        *,
        created_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        updated_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        merged_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        abandoned_histo: typing.Optional[typing.Iterable[global___Histo]] = ...,
        created: typing.Optional[global___ReviewCount] = ...,
        abandoned: builtins.int = ...,
        merged: builtins.int = ...,
        self_merged: builtins.int = ...,
        self_merged_ratio: builtins.float = ...,
        ttm_mean: builtins.float = ...,
        ttm_variability: builtins.float = ...,
        updates_of_changes: builtins.int = ...,
        changes_with_tests: builtins.float = ...,
        iterations_per_change: builtins.float = ...,
        commits_per_change: builtins.float = ...,
    ) -> None: ...
    def HasField(
        self, field_name: typing_extensions.Literal["created", b"created"]
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "abandoned",
            b"abandoned",
            "abandoned_histo",
            b"abandoned_histo",
            "changes_with_tests",
            b"changes_with_tests",
            "commits_per_change",
            b"commits_per_change",
            "created",
            b"created",
            "created_histo",
            b"created_histo",
            "iterations_per_change",
            b"iterations_per_change",
            "merged",
            b"merged",
            "merged_histo",
            b"merged_histo",
            "self_merged",
            b"self_merged",
            "self_merged_ratio",
            b"self_merged_ratio",
            "ttm_mean",
            b"ttm_mean",
            "ttm_variability",
            b"ttm_variability",
            "updated_histo",
            b"updated_histo",
            "updates_of_changes",
            b"updates_of_changes",
        ],
    ) -> None: ...

global___LifecycleStats = LifecycleStats

class RepoSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    FULLNAME_FIELD_NUMBER: builtins.int
    CREATED_CHANGES_FIELD_NUMBER: builtins.int
    ABANDONED_CHANGES_FIELD_NUMBER: builtins.int
    MERGED_CHANGES_FIELD_NUMBER: builtins.int
    UPDATED_CHANGES_FIELD_NUMBER: builtins.int
    OPEN_CHANGES_FIELD_NUMBER: builtins.int
    fullname: typing.Text = ...
    created_changes: builtins.int = ...
    abandoned_changes: builtins.int = ...
    merged_changes: builtins.int = ...
    updated_changes: builtins.int = ...
    open_changes: builtins.int = ...
    def __init__(
        self,
        *,
        fullname: typing.Text = ...,
        created_changes: builtins.int = ...,
        abandoned_changes: builtins.int = ...,
        merged_changes: builtins.int = ...,
        updated_changes: builtins.int = ...,
        open_changes: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "abandoned_changes",
            b"abandoned_changes",
            "created_changes",
            b"created_changes",
            "fullname",
            b"fullname",
            "merged_changes",
            b"merged_changes",
            "open_changes",
            b"open_changes",
            "updated_changes",
            b"updated_changes",
        ],
    ) -> None: ...

global___RepoSummary = RepoSummary

class ReposSummary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    REPOSUM_FIELD_NUMBER: builtins.int
    @property
    def reposum(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___RepoSummary
    ]: ...
    def __init__(
        self,
        *,
        reposum: typing.Optional[typing.Iterable[global___RepoSummary]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["reposum", b"reposum"]
    ) -> None: ...

global___ReposSummary = ReposSummary

class TermCount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TERM_FIELD_NUMBER: builtins.int
    COUNT_FIELD_NUMBER: builtins.int
    term: typing.Text = ...
    count: builtins.int = ...
    def __init__(
        self,
        *,
        term: typing.Text = ...,
        count: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["count", b"count", "term", b"term"]
    ) -> None: ...

global___TermCount = TermCount

class TermsCount(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    TERMCOUNT_FIELD_NUMBER: builtins.int
    TOTAL_HITS_FIELD_NUMBER: builtins.int
    total_hits: builtins.int = ...
    @property
    def termcount(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___TermCount
    ]: ...
    def __init__(
        self,
        *,
        termcount: typing.Optional[typing.Iterable[global___TermCount]] = ...,
        total_hits: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "termcount", b"termcount", "total_hits", b"total_hits"
        ],
    ) -> None: ...

global___TermsCount = TermsCount

class AuthorPeer(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTHOR_FIELD_NUMBER: builtins.int
    PEER_FIELD_NUMBER: builtins.int
    STRENGTH_FIELD_NUMBER: builtins.int
    author: typing.Text = ...
    peer: typing.Text = ...
    strength: builtins.int = ...
    def __init__(
        self,
        *,
        author: typing.Text = ...,
        peer: typing.Text = ...,
        strength: builtins.int = ...,
    ) -> None: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "author", b"author", "peer", b"peer", "strength", b"strength"
        ],
    ) -> None: ...

global___AuthorPeer = AuthorPeer

class AuthorsPeers(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTHOR_PEER_FIELD_NUMBER: builtins.int
    @property
    def author_peer(
        self,
    ) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[
        global___AuthorPeer
    ]: ...
    def __init__(
        self,
        *,
        author_peer: typing.Optional[typing.Iterable[global___AuthorPeer]] = ...,
    ) -> None: ...
    def ClearField(
        self, field_name: typing_extensions.Literal["author_peer", b"author_peer"]
    ) -> None: ...

global___AuthorsPeers = AuthorsPeers

class ChangesTops(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor = ...
    AUTHORS_FIELD_NUMBER: builtins.int
    REPOS_FIELD_NUMBER: builtins.int
    APPROVALS_FIELD_NUMBER: builtins.int
    @property
    def authors(self) -> global___TermsCount: ...
    @property
    def repos(self) -> global___TermsCount: ...
    @property
    def approvals(self) -> global___TermsCount: ...
    def __init__(
        self,
        *,
        authors: typing.Optional[global___TermsCount] = ...,
        repos: typing.Optional[global___TermsCount] = ...,
        approvals: typing.Optional[global___TermsCount] = ...,
    ) -> None: ...
    def HasField(
        self,
        field_name: typing_extensions.Literal[
            "approvals", b"approvals", "authors", b"authors", "repos", b"repos"
        ],
    ) -> builtins.bool: ...
    def ClearField(
        self,
        field_name: typing_extensions.Literal[
            "approvals", b"approvals", "authors", b"authors", "repos", b"repos"
        ],
    ) -> None: ...

global___ChangesTops = ChangesTops
