jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
        with:
          submodules: 'true'
      - uses: "cachix/install-nix-action@v15"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "cachix/cachix-action@v10"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: change-metrics
      - name: Run Test
        run: nix-build --no-out-link --attr ci
name: Nix
on:
  pull_request: {}
  push: {}
  release: {}
