jobs:
  compose:
    name: ubi-container-build-test
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "cachix/cachix-action@v12"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: change-metrics
      - name: Ensure cabal project override
        run: nix develop --command just codegen-cabal-override
      - name: Ensure cabal override file up to date
        run: git diff --exit-code
      - name: Build the container image
        run: docker build -f DockerfileUBI
name: DockerUBI
on:
  pull_request: {}
