jobs:
  publish-tag-nix-build:
    if: "github.repository_owner == 'change-metrics'"
    name: publish-tag-nix-build
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2.4.0"
      - uses: "cachix/install-nix-action@v20"
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: "cachix/cachix-action@v12"
        with:
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          name: change-metrics
      - name: Build the project
        run: nix build --no-link
name: Publish Tag Nix Build
on:
  push:
    tags:
      - "*"
